module.exports = {
  countryCodes: [
    { code: 'IN', isoCode: 'en' },
    { code: 'HI', isoCode: 'hi' },
    { code: 'ID', isoCode: 'id' },
    { code: 'MY', isoCode: 'ms' },
    { code: 'PH', isoCode: 'en' },
    { code: 'TH', isoCode: 'th' },
    { code: 'TW', isoCode: 'zh' },
    { code: 'AU', isoCode: 'en' },
    { code: 'NZ', isoCode: 'en' },
    { code: 'AR', isoCode: 'ar' },
    { code: 'ES', isoCode: 'es' },
    { code: 'JP', isoCode: 'jp' },
    { code: 'VN', isoCode: 'vi' },
    { code: 'DZ', isoCode: 'ar' },
    { code: 'EG', isoCode: 'ar' },
    { code: 'BD', isoCode: 'en' },
    { code: 'PK', isoCode: 'en' },
    { code: 'MM', isoCode: 'en' },
    { code: 'MX', isoCode: 'es' },
    { code: 'SA', isoCode: 'ar' },
  ],
  apiUrls: {
    IN: 'https://api.taboola.com/2.0/json/oppo-browser-india-en-push/recommendations.get',
    HI: 'https://api.taboola.com/2.0/json/oppo-browser-india-hindi-push/recommendations.get',
    ID: 'https://api.taboola.com/2.0/json/oppo-browser-indonesia-push/recommendations.get',
    MY: 'https://api.taboola.com/2.0/json/oppo-browser-malaysia-push/recommendations.get',
    PH: 'https://api.taboola.com/2.0/json/oppo-browser-philippine-push/recommendations.get',
    TH: 'https://api.taboola.com/2.0/json/oppo-browser-thailand-push/recommendations.get',
    TW: 'https://api.taboola.com/2.0/json/oppo-browser-tw-push/recommendations.get',
    AU: 'https://api.taboola.com/2.0/json/oppo-browser-au-push/recommendations.get',
    NZ: 'https://api.taboola.com/2.0/json/oppo-browser-nzl-push/recommendations.get',
    AR: 'https://api.taboola.com/2.0/json/oppo-browser-push-arabic/recommendations.get',
    ES: 'https://api.taboola.com/2.0/json/oppo-browser-push-spanish/recommendations.get',
    JP: 'https://api.taboola.com/2.0/json/oppo-browser-jp-push/recommendations.get',
    VN: 'https://api.taboola.com/2.0/json/oppo-browser-vn-push/recommendations.get',
    DZ: 'https://api.taboola.com/2.0/json/oppo-browser-push-arabic/recommendations.get',
    EG: 'https://api.taboola.com/2.0/json/oppo-browser-push-arabic/recommendations.get',
    BD: 'https://api.taboola.com/2.0/json/oppo-browser-push-englishfallback/recommendations.get',
    PK: 'https://api.taboola.com/2.0/json/oppo-browser-push-englishfallback/recommendations.get',
    MM: 'https://api.taboola.com/2.0/json/oppo-browser-push-englishfallback/recommendations.get',
    MX: 'https://api.taboola.com/2.0/json/oppo-browser-push-spanish/recommendations.get',
    SA: 'https://api.taboola.com/2.0/json/oppo-browser-push-arabic/recommendations.get',
    FALLBACK:
      'https://api.taboola.com/2.0/json/oppo-browser-push-englishfallback/recommendations.get',
  },
  apiSecret: 'bbdedea82872c8c2f24ca23a64a159dc',
  apiKey: 'bbdedea82872c8c2f24ca23a64a159dc',
};
